netmap: don't cause a mixed declaration error
Avoids:
..../LINUX/../sys/dev/netmap/netmap_generic.c: In function 'generic_netmap_rxsync':
..../LINUX/../sys/dev/netmap/netmap_generic.c:1006:25: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
  1006 |                         char *nmaddr = NMB(na, slot);
       |                         ^~~~